### ISSUE TITLE
Word 'let'

### ISSUE THREAD

**Issue by Alexey-T** [Nincraft/minetweaker-syntax-highlighting#2]
Why not hilited word "let",in this script? ex1.zs from GH.
~~~
id2(x1) =>

   id(x2) => (x2, x2)

   let id3 : Product<A> -> Product<A, A> = (x3) => id(

      x3)

   id4(x : Int) => x

   let y = id(id4(x1))

   return id3(((x4) => x4)(y))

id2(42)
~~~

**Comment by Nincodedo** [comment]
Could you post the whole script?

**Comment by Alexey-T** [comment]
https://github.com/keean/zenscript/blob/master/examples/ex1.zs

**Comment by Nincodedo** [comment]
That is not a Minetweaker script. This highlighting is specifically for Minetweaker.
